config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "iterable_events#index"
  # Defines the root path route ("/")
  resources :iterable_events
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/iterable_event.rb
class IterableEvent < ApplicationRecord 
  has_many :user_iterable_events
  has_many :users, through: :user_iterable_events
  validates :title, presence: true
  def create_event(type, title, user)
    if type == 'A'
      event = IterableEventPerformService::CreateEventService.new.user_event(user, title)
      return event.present?, event
    elsif type == 'B'
      event = IterableEventPerformService::CreateEventService.new.user_event(user, title)
      if event
        notification = IterableEventPerformService::NotificationService.new.notification(user, event.title)
        return [event.present?, notification.present?], [event, notification]
      else
        return [false, false], [nil, nil]
      end
    end
  end


  def update_event(my_event, user_ids)
    user_ids = user_ids.reject(&:blank?).map(&:to_i)
    event = IterableEventPerformService::UpdateEventService.new.event(user_ids, my_event)
    if event
      return event
    else
      return false
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :user_iterable_events
  has_many :iterable_events, through: :user_iterable_events
end

app/models/user_iterable_event.rb
class UserIterableEvent < ApplicationRecord
  belongs_to :user
  belongs_to :iterable_event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/iterable_events_controller.rb
class IterableEventsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_event, only: [:show, :edit, :update]


  def index
    @iterable_events = IterableEvent.all
  end
  
  def new
    @iterable_event = IterableEvent.new
  end

  def create
    @type = params[:iterable_event][:type]
    @title = params[:iterable_event][:title] 
    success, results = IterableEvent.new.create_event(@type, @title, current_user) 
    if success
      if @type == 'A'
        event = results
        flash[:success] = "Event created successfully"
        redirect_to iterable_events_path
      elsif @type == 'B'
        event, notification = results
        if event.present? && notification.present?
          flash[:success] = "Event and Notification created successfully"
          redirect_to iterable_events_path
        elsif event.present?
          flash[:error] = "Failed to create notification"
          redirect_to iterable_events_path
        else
          flash[:error] = "Failed to create event"
          redirect_to iterable_events_path
        end
      end
    else
      flash[:error] = "Failed to create event or notification"
      redirect_to iterable_events_path
    end
  end


  def show
  end

  def edit
  end

  def update
    user_ids = params[:user_ids]
    event = IterableEvent.new.update_event(@iterable_event, user_ids)
    if event
      flash[:notice] = "users added sucessfully"
      redirect_to iterable_event_path(event)
    else
      flash[:alert] = "not able to add users"
      redirect_to iterable_event_path(@iterable_event.id)
    end
  end


  private

  def set_event
    @iterable_event = IterableEvent.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/iterable_events/index.html.erb
<h2>All Events</h2>
<ul>
  <% @iterable_events.each do |event| %>
    <li>
      <%= link_to event.title, iterable_event_path(event['id']) %>
    </li>
  <% end %>
</ul>

app/views/iterable_events/new.html.erb
<%= form_with(model: @iterable_event, url: iterable_events_path, method: :post) do |form| %>
  <%= form.hidden_field :type, value: params[:type] %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit 'Create Event' %>
    <%= link_to 'Cancel', root_path, class: 'button' %>
  </div>
<% end %>

<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>

<% if flash[:alert] %>
  <div class="alert"><%= flash[:alert] %></div>
<% end %>

app/views/iterable_events/show.html.erb
<h1>Event Details</h1>

<p><strong>Title:</strong> <%= @iterable_event.title %></p>
<% if @iterable_event.users.any? %>
  <h2>Event Users:</h2>
  <ul>
    <% @iterable_event.users.each do |user| %>
      <li>
        <%= user.email %>
      </li>
    <% end %>
  </ul>
<% end %>

<%= form_with(model: @event, url: iterable_event_path(@iterable_event), method: :patch) do |form| %>
  <% users = User.where.not(id: current_user.id).map { |user| [user.email, user.id] }.compact %>
  <%= form.select :user_ids, users, {}, { multiple: true } %>
  <%= form.submit "Add Users" %>
<% end %>


<%= link_to 'Back to Events', iterable_events_path, class: 'btn btn-secondary' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "IterableTest" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%#= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%#= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%#= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%#= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%#= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">IterableTest</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse pull-right">
          <ul class="nav navbar-nav">
            <% if user_signed_in? %>
              <li><%= link_to 'Create Event A', new_iterable_event_path(event_type: 'A'), class: 'btn btn-primary btn-sm custom-style' %></li>
              <li><%= link_to 'Create Event B', new_iterable_event_path(event_type: 'B'), class: 'btn btn-primary btn-sm custom-style' %></li>
              <li><%= button_to "Sign out", destroy_user_session_path, method: :delete, class: 'btn btn-danger' %></li>
            <%end%>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2024</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>